-- CreateTable: users
-- This SQL is auto-generated by Prisma Migrate.
-- It creates the "users" table in PostgreSQL.

CREATE TABLE "users" (
    "user_id"         TEXT NOT NULL,
    "email"           TEXT NOT NULL,
    "password"        TEXT NOT NULL,
    "first_name"      TEXT NOT NULL,
    "last_name"       TEXT NOT NULL,
    "date_of_birth"   DATE NOT NULL,
    "profile_picture" TEXT,
    "bio"             TEXT,
    "is_active"       BOOLEAN NOT NULL DEFAULT true,
    "created_at"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"      TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("user_id")
);

-- CreateIndex: unique email
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- Note: Prisma also creates a _prisma_migrations table
-- to track which migrations have been applied.
